version: '3.6'

services:
  app1:
    volumes:
      - app1-root-sync:/app:nocopy
      - app1-appdata-sync:/app/data:nocopy
      - app1-nodemodules-sync:/app/node_modules:nocopy
  app2:
    volumes:
      - app2-root-sync:/app:nocopy
      - app2-appdata-sync:/app/data:nocopy
      - app2-nodemodules-sync:/app/node_modules:nocopy

volumes:
  app1-root-sync:
    external: true
  app1-appdata-sync:
    external: true
  app1-nodemodules-sync:
    external: true
  app2-root-sync:
    external: true
  app2-appdata-sync:
    external: true
  app2-nodemodules-sync:
    external: true
