version: '2'

# networks:
#    internal:
#        driver: bridge

services:
  app1:
#    build:
#      context: ./
#      dockerfile: Dockerfile.ci
    image: r.cfcr.io/ludx/dapp-shell-ci:feature
#    volumes:
#      - .:/app/
#      - ./data/app1:/app/data
#      - ./data/app1_node_modules:/app/node_modules
    expose:
      - 3100
    ports:
      - 3100:3100
#    networks:
#      - internal
#    privileged: true

    command: bin/ci-entrypoint.sh
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3100
      - APP_HOST=http://localhost
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=feature1.particl.xyz
      - MAINNET_PORT=52738
      - TESTNET_PORT=52935
    mem_reservation: 250000000
    mem_limit: 400000000
    memswap_limit: 400000000

#  app2:
#    image: r.cfcr.io/ludx/dapp-shell-ci:feature
#    expose:
#      - 3200
#    ports:
#      - 3200:3200
#    command: bin/ci-entrypoint.sh
#    env_file:
#      - .env.docker-compose
#    environment:
#      - NODE_ENV=development
#      - APP_PORT=3200
#      - RPCUSER=test
#      - RPCPASSWORD=test
#      - RPCHOSTNAME=feature2.particl.xyz
#      - MAINNET_PORT=53738
#      - TESTNET_PORT=53935
#    mem_reservation: 250000000
#    mem_limit: 500000000
#    memswap_limit: 1000000000


#  testrunner:
    # container_name: testrunner
#    image: r.cfcr.io/ludx/dapp-shell-ci:feature
#    command: bin/ci-testrunner.sh
#    depends_on:
#      - app1
    #  - app2
#    env_file:
#      - .env.docker-compose
#    environment:
#      - NODE_ENV=development
#      - APP_PORT=3100
#      - RPCUSER=test
#      - RPCPASSWORD=test
#      - RPCHOSTNAME=feature1.particl.xyz
#      - MAINNET_PORT=52738
#      - TESTNET_PORT=52935
#    mem_reservation: 250000000
#    mem_limit: 400000000
#    memswap_limit: 400000000

